# Funding / Sponsorship
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: # [your-github-username]
# open_collective: magb
# ko_fi: magb
# custom: ['https://magb.dev/sponsor']
